image: docker:stable

services:
  - docker:dind

before_script:
  - apk --no-cache add curl jq

kick-e2e:
    tags:
        - docker
    stage: deploy
    script:
      - set -e

      # kick e2e
      - >-
        E2E_PIPELINE_ID=`curl
        --header "PRIVATE-TOKEN: $CI_CUSTOM_CI_PAT"
        "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/trigger/pipeline"`
      - >- 
        echo $?
        echo $E2E_PIPELINE_ID

      # poll for it to finish
      - >-
        while [ -z $PIPELINE_STATUS ] || [ $PIPELINE_STATUS = "pending" ] || [ $PIPELINE_STATUS = "running" ]; do
          PIPELINE_STATUS=`curl \
            --silent \
            --header "PRIVATE-TOKEN: $CI_CUSTOM_CI_PAT" \
            "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/pipelines/$E2E_PIPELINE_ID" | jq -r ".status"`
          echo "waiting for e2e pipeline ...";
          sleep 5;
        done

      # check for success
      - >-
        if [ $PIPELINE_STATUS != "success" ]; then
          echo "failure further down the pipeline; PIPELINE_STATUS is $PIPELINE_STATUS"
          exit 1
        fi


